from wx import Control, CommandEvent
from mock_wx.test_case import BaseClass
DefaultSize = {"DefaultSize"}
EVT_BUTTON = {"EVT_BUTTON"}
EVT_ENTER_WINDOW = {"EVT_ENTER_WINDOW"}
EVT_KEY_DOWN = {"EVT_KEY_DOWN"}
EVT_KEY_UP = {"EVT_KEY_UP"}
EVT_KILL_FOCUS = {"EVT_KILL_FOCUS"}
EVT_LEAVE_WINDOW = {"EVT_LEAVE_WINDOW"}
EVT_LEFT_DOWN = {"EVT_LEFT_DOWN"}
EVT_LEFT_UP = {"EVT_LEFT_UP"}
EVT_MOTION = {"EVT_MOTION"}
EVT_MOUSE_CAPTURE_LOST = {"EVT_MOUSE_CAPTURE_LOST"}
EVT_PAINT = {"EVT_PAINT"}
EVT_SET_FOCUS = {"EVT_SET_FOCUS"}
EVT_SIZE = {"EVT_SIZE"}
class GenButton(Control): ...
class GenBitmapButton(GenButton): ...
class GenBitmapTextButton(GenBitmapButton): ...
class GenButtonEvent(CommandEvent): ...
class __ThemedMixin(BaseClass): ...
class ThemedGenBitmapButton(__ThemedMixin, GenBitmapButton): ...
class ThemedGenBitmapTextButton(__ThemedMixin, GenBitmapTextButton): ...
class ThemedGenButton(__ThemedMixin, GenButton): ...
class __ToggleMixin(BaseClass): ...
class GenBitmapTextToggleButton(__ToggleMixin, GenBitmapTextButton): ...
class GenBitmapToggleButton(__ToggleMixin, GenBitmapButton): ...
class GenToggleButton(__ToggleMixin, GenButton): ...
class ThemedGenBitmapTextToggleButton(__ThemedMixin, GenBitmapTextToggleButton): ...
class ThemedGenBitmapToggleButton(__ThemedMixin, GenBitmapToggleButton): ...
class ThemedGenToggleButton(__ThemedMixin, GenToggleButton): ...
