class GLCanvas(Window): ...
WX_GL_RGBA = {"WX_GL_RGBA"}
class GLContext(Object): ...
class GLAttributes(GLAttribsBase): ...
class GLContextAttrs(GLAttribsBase): ...
class GLAttribsBase: ...
OR = {"OR"}
