from wx.base_class import BaseClass
from wx import Object, Window
OR = {"OR"}
WX_GL_RGBA = {"WX_GL_RGBA"}
class GLAttribsBase(BaseClass):
    Size = {"Size"}
class GLAttributes(GLAttribsBase): ...
class GLCanvas(Window): ...
class GLContext(Object): ...
class GLContextAttrs(GLAttribsBase): ...
