from wx import Control, ItemContainer, TextEntry
from wx.lib.masked.maskededit import MaskedEditAccessorsMixin, MaskedEditMixin
class ComboBox(Control, ItemContainer, TextEntry): ...
class BaseMaskedComboBox(ComboBox, MaskedEditMixin): ...
class PreMaskedComboBox(BaseMaskedComboBox, MaskedEditAccessorsMixin): ...
