from wx import ItemContainer, Control, TextEntry
from wx.lib.masked.maskededit import MaskedEditMixin, MaskedEditAccessorsMixin
class ComboBox(Control, ItemContainer, TextEntry): ...
class BaseMaskedComboBox(ComboBox, MaskedEditMixin): ...
class PreMaskedComboBox(BaseMaskedComboBox, MaskedEditAccessorsMixin): ...
