from mock_wx.test_case import BaseClass
class AuiDefaultTabArt(BaseClass): ...
class ChromeTabArt(AuiDefaultTabArt): ...
class FF2TabArt(AuiDefaultTabArt): ...
class VC71TabArt(AuiDefaultTabArt): ...
class VC8TabArt(AuiDefaultTabArt): ...
