from wx.lib.masked.textctrl import BaseMaskedTextCtrl
from mock_wx._test_case import BaseClass
class NumCtrlAccessorsMixin(BaseClass): ...
class NumCtrl(BaseMaskedTextCtrl, NumCtrlAccessorsMixin): ...
