from wx.lib.masked.maskededit import MaskedEditAccessorsMixin, MaskedEditMixin
from wx import Control, TextEntry
class TextCtrl(Control, TextEntry): ...
class BaseMaskedTextCtrl(TextCtrl, MaskedEditMixin): ...
class PreMaskedTextCtrl(BaseMaskedTextCtrl, MaskedEditAccessorsMixin): ...
