from wx.lib.masked.textctrl import BaseMaskedTextCtrl
from mock_wx.test_case import BaseClass
class IpAddrCtrlAccessorsMixin(BaseClass): ...
class IpAddrCtrl(BaseMaskedTextCtrl, IpAddrCtrlAccessorsMixin): ...
