from wx.lib.masked.textctrl import BaseMaskedTextCtrl
from wx.base_class import BaseClass
class IpAddrCtrlAccessorsMixin(BaseClass): ...
class IpAddrCtrl(BaseMaskedTextCtrl, IpAddrCtrlAccessorsMixin): ...
