from wx import PyCommandEvent
from wx.lib.masked.textctrl import BaseMaskedTextCtrl
from wx.base_class import BaseClass
class TimeCtrl(BaseMaskedTextCtrl): ...
class TimeCtrlAccessorsMixin(BaseClass): ...
class TimeUpdatedEvent(PyCommandEvent): ...
