from wx import Control, NotifyEvent
EVT_MEDIA_FINISHED = {"EVT_MEDIA_FINISHED"}
EVT_MEDIA_LOADED = {"EVT_MEDIA_LOADED"}
EVT_MEDIA_PAUSE = {"EVT_MEDIA_PAUSE"}
EVT_MEDIA_PLAY = {"EVT_MEDIA_PLAY"}
EVT_MEDIA_STATECHANGED = {"EVT_MEDIA_STATECHANGED"}
EVT_MEDIA_STOP = {"EVT_MEDIA_STOP"}
MC_NO_AUTORESIZE = {"MC_NO_AUTORESIZE"}
MEDIACTRLPLAYERCONTROLS_DEFAULT = {"MEDIACTRLPLAYERCONTROLS_DEFAULT"}
MEDIACTRLPLAYERCONTROLS_NONE = {"MEDIACTRLPLAYERCONTROLS_NONE"}
MEDIACTRLPLAYERCONTROLS_STEP = {"MEDIACTRLPLAYERCONTROLS_STEP"}
MEDIACTRLPLAYERCONTROLS_VOLUME = {"MEDIACTRLPLAYERCONTROLS_VOLUME"}
MEDIASTATE_PAUSED = {"MEDIASTATE_PAUSED"}
MEDIASTATE_PLAYING = {"MEDIASTATE_PLAYING"}
MEDIASTATE_STOPPED = {"MEDIASTATE_STOPPED"}
MediaCtrlPlayerControls = {"MediaCtrlPlayerControls"}
MediaState = {"MediaState"}
class MediaCtrl(Control):
    BestSize = {"BestSize"}
    PlaybackRate = {"PlaybackRate"}
    State = {"State"}
    Volume = {"Volume"}
class MediaEvent(NotifyEvent): ...
